import { GoogleAnalytics } from "@next/third-parties/google";

import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import RecoilProvider from "@/providers/RecoilProvider";
import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SnapStyle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <GoogleAnalytics gaId="G-KL8HBX29J6" />

      <body className={`${inter.className} flex flex-col h-screen text-base`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <RecoilProvider>
            <TooltipProvider>
              <Header />
              {children}
            </TooltipProvider>
          </RecoilProvider>
          <Toaster position="bottom-left" />
        </ThemeProvider>
      </body>
    </html>
  );
}
